# This configuration is intended for development purpose, it's **your** responsibility to harden it for production
version: '3.8'
services:
  ybdbdemo-app:
    image: humourmind/ybdb-xp:1.0.0
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,api-docs
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:yugabytedb://ybdb:5433/ybdbdemo
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
    ports:
      - 127.0.0.1:8080:8080
  ybdb:
    container_name: ybdb
    image: yugabytedb/yugabyte:2.14.7.0-b51
    environment:
      - YSQL_PASSWORD=ybdbdemo
      - YSQL_USER=ybdbdemo
      - YSQL_DB=ybdbdemo
    # volumes:
    #   - ~/volumes/jhipster/ybdbdemo/ybdb/:/var/lib/ybdb/data/
    # If you want to expose these ports outside your dev PC,
    # remove the "127.0.0.1:" prefix
    ports:
      - 5433:5433
      - 7000:7000
      - 9000:9000
      - 13000:13000
    command: bin/yugabyted start --base_dir=/mnt/disk0 --background=false
